name: Zordon AI code reviewer
on:
  pull_request:
    branches:
      - main
      - test/codereviewer-2
    types: [opened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: CodeReview
        uses: zordonai/codereviewer@v1.0.0-beta.1
        with:
          github_token: ${{ secrets.GLOBAL_GITHUB_TOKEN }}
          palm_api_key: ${{ secrets.PALM_API_KEY }}
