name: Zordon AI code reviewer
on:
  pull_request:
    branches:
      - main
      - test/codereviewer-4
    types: [opened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Initializing
        uses: actions/checkout@v3
      - name: CodeReview
        uses: zordonai/codereviewer@main
        with:
          github_token: ${{ secrets.GLOBAL_GITHUB_TOKEN }}
          bard_api_cookie: ${{ secrets.BARD_API_COOKIE }}
